add new plugins

diff --git a/vimfect b/vimfect
--- a/vimfect
+++ b/vimfect
@@ -1,24 +1,33 @@
 #!/bin/bash
 #
-## Add a git submodule to the repository
+## Add git submodules to the repository
+
 set -euo pipefail
 set -x
 
-# Check if the user has provided a github url
-if [ "$1" = "" ]; then
-	echo "Please provide a github url"
+die() {
+	printf "\e[31m%s\e[0m\n" "$*"
 	exit 1
-fi
+}
 
-github_url=$1
+add_submodule() {
+	local url="$1"
+	[[ "$url" =~ ^https://github.com ]] \
+		&& github_url="${url%%\?*}" \
+		|| github_url="https://github.com/${url}.git"
+	# TODO
 
-# if the githuburl doesnt begin with https://github.com, then add it
-if [[ ! "$github_url" =~ ^https://github.com ]]; then
-	github_url="https://github.com/${github_url}.git"
-fi
+	PLUGIN_DIR="${HOME}/.vim/pack/vimfect/opt"
+	mkdir -p "$PLUGIN_DIR"
+	cd "$PLUGIN_DIR" || die "Failed to change directory to $PLUGIN_DIR"
 
-PLUGIN_DIR="${HOME}/.vim/pack/vimfect/opt"
-mkdir -p "$PLUGIN_DIR"
-cd "$PLUGIN_DIR" || exit 1
+	git submodule add --force --depth 1 --progress "$github_url"
+}
 
-git submodule add --depth=1 --force "$github_url"
+# Check if the user has provided at least one  url
+[[ $# -gt 0 ]] || die "Usage: $0 <url>..."
+
+while [[ $# -gt 0 ]]; do
+	add_submodule "$1"
+	shift
+done
